const Products = [
  // Shirts
  {
    id: 1,
    title: "White Shirt",
    category: "shirt",
    image: "/assets/images/image (7).png",
    text: "Shop the latest in denim styles.",
    price: 1200,
    rating: 4,
  },
  {
    id: 2,
    title: "WAFFLE LONG SELEEVES",
    category: "shirt",
    image: "/assets/images/image (4).png",
    text: "Shop the latest in denim styles.",
    price: 2000,
    rating: 5,
  },
  {
    id: 3,
    title: "TEES",
    category: "shirt",
    image: "/assets/images/image (6).png",
    text: "Trendy collections of tees.",
    price: 13000,
    rating: 3,
  },
  {
    id: 4,
    title: "ORGANIC CREW",
    category: "shirt",
    image: "/assets/images/image (10).png",
    text: "Explore sweaters fashion ",
    price: 1800,
    rating: 4,
  },
  {
    id: 5,
    title: "SHIRT",
    category: "shirt",
    image: "/assets/images/image.png",
    text: "Explore men’s fashion.",
    price: 1500,
    rating: 2,
  },
  {
    id: 6,
    title: "TEES",
    category: "shirt",
    image: "/assets/images/image (5).png",
    text: "Trendy collections of tees.",
    price: 1000,
    rating: 5,
  },

  // Jeans
  {
    id: 11,
    title: "DENIM",
    category: "jeans",
    image: "/assets/images/image (1).png",
    text: "Shop the latest in denim styles.",
    price: 1200,
    rating: 4,
  },
  {
    id: 12,
    title: "DRESS PAINT",
    category: "jeans",
    image: "/assets/images/image (3).png",
    text: "Explore sweaters fashion ",
    price: 1500,
    rating: 3,
  },
  {
    id: 13,
    title: "WOMEN BOTTOMS",
    category: "jeans",
    image: "/assets/images/image (11).png",
    text: "Trendy collections of tees.",
    price: 1000,
    rating: 5,
  },
  {
    id: 14,
    title: "DRESS PAINT",
    category: "jeans",
    image: "/assets/images/image (3).png",
    text: "Explore sweaters fashion ",
    price: 1800,
    rating: 4,
  },
  {
    id: 15,
    title: "BROWN PAINT",
    category: "jeans",
    image: "/assets/images/image (12).png",
    text: "Explore sweaters fashion ",
    price: 1500,
    rating: 4,
  },
];

export default Products;
